/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javasoru;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ckmz
 */
public class ogretmenhatali extends javax.swing.JFrame {

    /**
     * Creates new form ogretmenhatali
     */
    public ogretmenhatali() {
        initComponents();
        try{
            listele();
        }
        catch(Exception ex){
            Logger.getLogger(ogretmengiris.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
     public void listele(){
        com.mysql.jdbc.Connection con;
        try {

        Class.forName("com.mysql.jdbc.Driver");

        con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javasoru?autoReconnect=true&useSSL=false","root","0001");
        Statement st = (Statement) con.createStatement();

        try (ResultSet rs = st.executeQuery("Select * from adminhatali")) {
            int colcount = rs.getMetaData().getColumnCount();

            DefaultTableModel tm = new DefaultTableModel(); 

            for(int i = 1;i<=colcount;i++)

                tm.addColumn(rs.getMetaData().getColumnName(i)); 

            while(rs.next())

                {

                    Object[] row = new Object[colcount];

                    for(int i=1;i<=colcount;i++)

                        row[i-1] = rs.getObject(i);

                    tm.addRow(row);

                }

            jTable1.setModel(tm);

        }

        con.close();

    } catch (SQLException ex) {

        Logger.getLogger(ogretmengiris.class.getName()).log(Level.SEVERE,null,ex);

    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmengiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("İD");

        jLabel2.setText("SORU");

        jLabel3.setText("A");

        jLabel4.setText("B");

        jLabel5.setText("C");

        jLabel6.setText("D");

        jLabel7.setText("BRANŞ");

        jLabel8.setText("SEVİYE");
        jLabel8.setToolTipText("");

        jLabel9.setText("DOĞRU CEVAP");

        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SORU DOĞRU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SORU YANLIŞ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ogrthome geri=new ogrthome();
        geri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
ogretmengiris ogretmen = new ogretmengiris();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              try{
            int soru = JOptionPane.showConfirmDialog(null, "SORUNUN DOĞRU OLDUĞUNDAN EMİN MİSİNİZ?","Uyarı",JOptionPane.YES_NO_CANCEL_OPTION);
             if(soru==0){
                  if(ogretmen.brans.equals(String.valueOf(jTextField7.getText()))){
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javasoru?autoReconnect=true&useSSL=false","root","0001");
            String sil="DELETE FROM adminhatali WHERE id=?";
            java.sql.PreparedStatement st=conn.prepareStatement(sil);
            st.setString (1, jTextField1.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Başarılı.");
            listele();
          jTextField1.setText("");  jTextField2.setText("");  jTextField3.setText("");  jTextField4.setText(""); 
          jTextField5.setText(""); jTextField6.setText(""); jTextField7.setText(""); jTextField8.setText(""); jTextField9.setText("");
             }
                  else{  JOptionPane.showMessageDialog(null,"KENDİ ALANINIZDA OLMAYAN SORU HAKKINDA KARAR VEREMEZSİNİZ.");}
             }
             else{}

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
          int satir = jTable1.getSelectedRow(); //Seçilen satırı bulduk

    jTextField1.setText(String.valueOf(jTable1.getValueAt(satir,0)));
    jTextField2.setText(String.valueOf(jTable1.getValueAt(satir,1)));
    jTextField3.setText(String.valueOf(jTable1.getValueAt(satir,2)));
    jTextField4.setText(String.valueOf(jTable1.getValueAt(satir,3)));
    jTextField5.setText(String.valueOf(jTable1.getValueAt(satir,4)));
    jTextField6.setText(String.valueOf(jTable1.getValueAt(satir,5)));
    jTextField7.setText(String.valueOf(jTable1.getValueAt(satir,6)));
    jTextField8.setText(String.valueOf(jTable1.getValueAt(satir,7)));
    jTextField9.setText(String.valueOf(jTable1.getValueAt(satir,8)));
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {  
             if(ogretmen.brans.equals(String.valueOf(jTextField7.getText()))){
            com.mysql.jdbc.Connection baglanti=(com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javasoru?autoReconnect=true&useSSL=false","root","0001");
            String ekle = " insert into kesinhatali (id,soru,a,b,c,d,dersadi,seviye,dogrucevap) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement preparedStmt = baglanti.prepareStatement(ekle);
                 preparedStmt.setInt (1, Integer.parseInt(jTextField1.getText()));
		 preparedStmt.setString (2, jTextField2.getText());
		 preparedStmt.setString (3, jTextField3.getText());
                 preparedStmt.setString (4, jTextField4.getText());
		 preparedStmt.setString (5, jTextField5.getText());
                 preparedStmt.setString (6, jTextField6.getText());
		 preparedStmt.setString (7, jTextField7.getText());
                 preparedStmt.setString (8, jTextField8.getText());
                 preparedStmt.setString (9, jTextField9.getText());
		 preparedStmt.execute();
		 baglanti.close();     
                 JOptionPane.showMessageDialog(this, "Hatalı soru kaldırıldı");
             }
             else{ JOptionPane.showMessageDialog(this, "KENDİ ALANINIZ DIŞINDA SORU SİLEMEZSİNİZ.");}
        } catch (SQLException ex) {
            Logger.getLogger(ogretmengiris.class.getName()).log(Level.SEVERE, null, ex);
        }
           try{
           
                  if(ogretmen.brans.equals(String.valueOf(jTextField7.getText()))){
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javasoru?autoReconnect=true&useSSL=false","root","0001");
            String sil="DELETE FROM sorular WHERE id=?";
            java.sql.PreparedStatement st=conn.prepareStatement(sil);
            st.setString (1, jTextField1.getText());
            st.executeUpdate();
          
            listele();
//          jTextField1.setText("");  jTextField2.setText("");  jTextField3.setText("");  jTextField4.setText("");  jTextField5.setText(""); jTextField6.setText("");
             }
                  else{ JOptionPane.showMessageDialog(null,"KENDİ ALANINIZ DIŞINDA SORU SİLEMEZSİNİZ.");
//                    jTextField1.setText("");  jTextField2.setText("");  jTextField3.setText("");  jTextField4.setText("");  jTextField5.setText(""); jTextField6.setText("");
    }
             
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
            try{
           
                  if(ogretmen.brans.equals(String.valueOf(jTextField7.getText()))){
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javasoru?autoReconnect=true&useSSL=false","root","0001");
            String sil="DELETE FROM adminhatali WHERE id=?";
            java.sql.PreparedStatement st=conn.prepareStatement(sil);
            st.setString (1, jTextField1.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Başarılı.");
            listele();
             }
                  else{ JOptionPane.showMessageDialog(null,"KENDİ ALANINIZ DIŞINDA SORU SİLEMEZSİNİZ.");
                    jTextField1.setText("");  jTextField2.setText("");  jTextField3.setText("");  jTextField4.setText("");  jTextField5.setText(""); jTextField6.setText("");
    }
             
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
              jTextField1.setText("");  jTextField2.setText("");  jTextField3.setText("");  jTextField4.setText("");  jTextField5.setText(""); jTextField6.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogretmenhatali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogretmenhatali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogretmenhatali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogretmenhatali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogretmenhatali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
